### ISSUE TITLE
Errors after update.

### ISSUE THREAD

**Issue by MRDzA** [igdmapps/igdm-pro-release#4]
![2019-04-03_171153](https://user-images.githubusercontent.com/49244251/55490466-14dfa500-5634-11e9-9177-9f2ee8c77ca4.jpg)
![2019-04-03_171205](https://user-images.githubusercontent.com/49244251/55490469-1610d200-5634-11e9-8353-7178e53f033b.jpg)

**Comment by ifedapoolarewaju** [comment]
this is fixed now. please restart your app to install the latest update

**Comment by MRDzA** [comment]
Sorry, this one with smileys and stickers is not fixed. I still see ? ? ? ? ? ? ? ? ? instead of pictures.

**Comment by ifedapoolarewaju** [comment]
what operating system are you using? Did this only show up after the update? or was it always that way?

**Comment by MRDzA** [comment]
It was OK earlier, it crashed after update. I use Win 10 Pro.

I was using free version before update, I have bought Pro version few days ago.
